export type GetMarketResponse = {
  id: number;
  obra: string | null;
  pep: string | null;
  diagrama: string | null;
  entrada: Date | null;
  municipio: number | null;
  tipo: number | null;
  parceira: number | null;
  circuito: number | null;
  prazo: number | null;
  prazoTotal: Date | null;
  prazoTexto: string | null;
  moEmpresa: number | null;
  moCliente: number | null;
  moPlanejada: number | null;
  referencia: string | null;
  observacao: string | null;
  statusOv: number | null;
  statusPep: string | null;
  statusDiagrama: string | null;
  equipeNumPedido: string | null;
};
