version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dev/Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./dev:/src
      - /src/node_modules
    networks:
      - my-network
    depends_on:
      - db
    command: npm run start:dev

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
    volumes:
      - ./client:/src
      - /src/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
