import type { Metadata } from "next";
import '@/globals.css';

import { UserProvider } from '@/contexts/userContext';

export const metadata: Metadata = {
  title: "Gestão de obras CCM - São Paulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
