import type { Metadata } from "next";
import "@/globals.css";
import { UserProviderWrapper } from "@/components/login/UserProviderWrapper";
import { EmotionCacheProvider } from "@/theme/emotionCache";

export const metadata: Metadata = {
  title: "Gestão de obras CCM - São Paulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <UserProviderWrapper>{children}</UserProviderWrapper>
      </body>
    </html>
  );
}
