import type { Metadata } from "next";
import "@/globals.css";

import { UserProvider } from "@/contexts/userContext";
import { MapFilterProvider } from "@/contexts/mapFilterContext";
import { SidebarProvider } from "@/contexts/sidebarContext";

export const metadata: Metadata = {
  title: "Gestão de obras CCM - São Paulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <UserProvider>
          <SidebarProvider>
            <MapFilterProvider>{children}</MapFilterProvider>
          </SidebarProvider>
        </UserProvider>
      </body>
    </html>
  );
}
