export const SERVICE_OPERATIONS: string[] = [
  "INSTALAÇÃO",
  "DESATIVAÇÃO",
  "SUBSTITUIR APLICAR",
  "SUBSTITUIR RETIRADA",
] as const;

export const MATERIAL_OR_SERVICE_OPTIONS = [
  "Todos",
  "Material",
  "Serviço",
] as const;

export const SERVICE_AND_MATERIAL_FAMILIES = [
  "BANCO CAPAC. PARALELO",
  "CÂMARA (REDE SUBTERR)",
  "CANALETA (REDE SUBTERR)",
  "CH. FUSÍVEL >= 34,5KV",
  "CH. FUSÍVEL RELIGADORA",
  "CHAVE ASSOCIADA BC",
  "CHAVE SECCIONADORA",
  "CHAVE SECCIONALIZADOR",
  "CHAVE TANDEM",
  "CONC. PRIM. DE MEDIÇÃO",
  "CONC. SEC. DE MEDIÇÃO",
  "CONDUTO (REDE SUBTERR)",
  "CONDUTOR (VÃO/RM LIG)",
  "ESTR SUPORTE REGULADOR",
  "GALERIA (REDE SUBTERR)",
  "LUMINÁRIA",
  "MEDIDOR BTZERO",
  "PÁRA-RAIOS >= 34,5KV",
  "POSTE",
  "REGULADOR DE TENSÃO",
  "RELIGADOR",
  "R-RAMAL LIGAÇÃO",
  "TRAFO PED/PLATAF/ESTAL",
  "TRANSF DISTR SUBTERR.",
  "TRANSF DISTR. SUBMERS.",
  "TRANSF. DISTR. AÉREO",
];
